server:
  port: 18089  #服务端口
  host: 0.0.0.0 #监听所有网络接口
  logger:
#    file: logs/app.log
    level: DEBUG # 日志级别: CRITICAL, ERROR, WARNING, INFO, DEBUG

db:
  url: "mysql+pymysql://root:itcast321bca@192.168.150.101:3306/agent_center?charset=utf8mb4&connect_timeout=10"
  pool_size: 10           # 连接池大小
  max_overflow: 20        # 超出连接池的最大连接数
  pool_timeout: 30        # 池中无连接时的等待时间
  pool_recycle: 1800      # 连接回收时间（秒）
  echo: True               # 控制台输出 SQL

jwt:
  private_key: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKIIk0LxLhUHchzhJ8A607DYSeAgSrPSS5GPdh8vDJshIkgK9YBxEBcqv5km/xyHgpE45FsyQSB5/fXph/ywwgNumYTZUUyt3yi+ygvfZyvpwo4Cz6Jzwp5M2doiG7lKryv0MbIsM3Rs5KU0BOAsMiVVt5LdeM3SSb1lHaQj5zdNAgMBAAECgYACCmxoYTpv8110wnUwtTNc79LTKs6MczwwA7si62gtb/5kvLAydobgWjgT74TMN2MY/YfXijHkMDhXNFWNHi2WiyScGaN3+YesxFUoG5H/2hQAUcDzj1Rryh+gerkWdqoFbGu3d+v5kur+w36VTCD3qpHyADycM//UA7yKb+8i4QJBANQyPNwOUJabDlLjTd42GzvAZTE6gmPrOopsRnHW8TVIHkHXexCMQLQ4TTg6Ct5ShuSTAgYUGPQv3jxpLts+fcUCQQDDe22AtsqnKVaG2KYVYWFLnI3hYNw8wePepZbt/87MPgYtkEc5WjFF/QUlHwLcpc7YW6hrJYwMbZvOB7YVHrPpAkAlbQLs8R1nosuA9RRb2AEvpbxzVVWAGBIILhayp219r02e4UmUXphe8Ps1qo8WLUobcI5P0iWgk/zHfOnFw5zdAkEAh2o+PfbiRZAeT4VO7+qocq99nY3yougRiU+eUTpusA+bSf7zR+iRz5Dp+oAUBHOb6Ub9UVQOQyG+16eB2/mL2QJBAIMjhAu5kTZAWVDpuJ6AtDodscuZQs8EOCdU7hx+aJUMC4K1aeuwD9QhkOZtpA/V2BzgNcqWt5dfntU2ovQ0g1U="
  public_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCiCJNC8S4VB3Ic4SfAOtOw2EngIEqz0kuRj3YfLwybISJICvWAcRAXKr+ZJv8ch4KROORbMkEgef316Yf8sMIDbpmE2VFMrd8ovsoL32cr6cKOAs+ic8KeTNnaIhu5Sq8r9DGyLDN0bOSlNATgLDIlVbeS3XjN0km9ZR2kI+c3TQIDAQAB"
  expire_hours: 720 #token有效期，单位小时